In [1]:
!nvidia-smi

Sat Sep  7 22:20:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensors are created using `torch.tensor()` : https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tesnor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR  =torch.tensor([[[1,2,3],
                         [3, 6, 9],
                         [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### RANDOM TENSORS

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers --> look at data --> update random variables --> look at data --> update random numbers`

In [17]:
# Create random tensors of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9964, 0.6635, 0.1500, 0.6334],
        [0.0198, 0.3299, 0.7645, 0.3678],
        [0.5433, 0.4981, 0.1103, 0.2169]])

In [18]:
random_tensor.ndim
# in a nutshell, ndim refers to how many pairs of square brackets do we have?

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-24-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
torch.__version__

'2.4.0+cu121'

In [26]:
# Use torch.arange()
one_to_ten = torch.arange(start =0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is the tensor
                               device= None, # What device is your tensor on?
                               requires_grad= False) # Whether or not to track gradience with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device= None,
                               requires_grad= False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (these are tensor aatributes)

1. Tensors not right datatype :to get the datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape :to get the shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device :to get the device from a tensor, can use `tensor.device`


In [35]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6189, 0.8838, 0.4494, 0.7319],
        [0.6872, 0.3129, 0.5972, 0.2877],
        [0.6011, 0.0114, 0.6485, 0.4030]])

In [36]:
# Find out the details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6189, 0.8838, 0.4494, 0.7319],
        [0.6872, 0.3129, 0.5972, 0.2877],
        [0.6011, 0.0114, 0.6485, 0.4030]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Additions
* Subraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# Subract 10
tensor -10

tensor([-9, -8, -7])

In [40]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of perdorming multiplication in neural networks and deep learning:
1. Element-wise Multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3), @ (3,2)` will work
* `(3,2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> (2,2)
* `(3,2) @ (2,3)` -> (3,3)

In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Matrix multiplication broken
1*1 + 2*2 + 3*3

14

In [45]:
tensor@tensor

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 0 ns, total: 1.65 ms
Wall time: 3.79 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 50 µs, total: 50 µs
Wall time: 54.1 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [10, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**
A **transpose** switches the axes or dimensions of a given tensor

In [49]:
tensor_B.T

tensor([[ 7, 10,  9],
        [ 8, 11, 12]])

In [50]:
tensor_B.T.shape

torch.Size([2, 3])

In [51]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  32,  33],
        [ 53,  74,  75],
        [ 83, 116, 117]])

In [52]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor A: {tensor_A.shape}, tensor B: {tensor_B.shape}")
print(f"New shapes: tensor A: {tensor_A.shape}, tensor B: {tensor_B.T.shape}")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor A: torch.Size([3, 2]), tensor B: torch.Size([3, 2])
New shapes: tensor A: torch.Size([3, 2]), tensor B: torch.Size([2, 3])
Output: 

tensor([[ 23,  32,  33],
        [ 53,  74,  75],
        [ 83, 116, 117]])
Output shape: torch.Size([3, 3])


## Finding min, max, mean, sum, etc. (tensor aggregation)

In [53]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [54]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [55]:
# Find the max
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find the mean
torch.mean(x.type(torch.float32)) # we need to convert the long dtype into floating or complex dtype to use mean

tensor(46.)

In [57]:
x.type(torch.float32).mean()

tensor(46.)

In [58]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [59]:
# Find the position in tensor that has the minimum value with `torch.argmin()`
x.argmin()

tensor(0)

In [60]:
x[0]

tensor(1)

In [61]:
# Find the position in the tensor that has maximum value
x.argmax()

tensor(9)

In [62]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, unsqueezing

* Reshaping: reshapes an input tensor to a defined shape
* View: return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: Removes all `1` dimensions from a tensor
* Unsqueeze: Add a `1` dimension to a target tensor
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way.

In [63]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Changing z changes x (because a view of tensor shares the same memory as the original one)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [68]:
# Stack tensors on top of each other
x_stacked_2 = torch.stack([x,x,x,x], dim = 0)
x_stacked_2

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [69]:
# torch.squeeze() - removes all single dimensions from target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_reshaped.squeeze().shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [70]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [71]:
# Add an extra dimension with unsqueeze
x_unsqueezed_2 = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed_2}")
print(f"New shape: {x_unsqueezed_2.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [72]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified
x_original = torch.rand(size = (224, 224, 3)) # height, width, colour channels

# Permute the original tensor to rearrange the axis (or dims) order
x_permute = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


##### A little explanation
In this code, you have a tensor `x_original` of size `(224, 224, 3)` which represents an image with height `224`, width `224`, and 3 color channels (e.g., RGB).

Here’s a breakdown of the permute operation:

- **`x_original.permute(2, 0, 1)`**: This operation rearranges the dimensions (axes) of the tensor based on the order of indices provided. Each number corresponds to the current axis' position.
  - The original dimensions of `x_original` are `(height, width, channels)` or `(224, 224, 3)`.
  - `permute(2, 0, 1)` means:
    - The dimension at index `2` (which is `3`, the color channels) moves to the front.
    - The dimension at index `0` (which is `224`, the height) moves to the second position.
    - The dimension at index `1` (which is `224`, the width) moves to the last position.

So, the new shape of `x_permute` becomes `(3, 224, 224)` where the first axis represents the color channels, and the last two represent height and width.

This is commonly done to change the layout from `HWC` (Height, Width, Channels) format to `CHW` (Channels, Height, Width) format, which is often required by certain deep learning libraries such as PyTorch for processing images.

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [73]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
# Let's index on the tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [76]:
x[0, 0]

tensor([1, 2, 3])

In [77]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [78]:
x[0][1][1]

tensor(5)

In [79]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [81]:
# Get all values of the 0 dimension but only the 1 index of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [82]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [83]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

In [84]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has fucnitonality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [85]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# Change the value of array, what will happen to "tensor"?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [88]:
numpy_tensor.dtype

dtype('float32')

In [89]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability

In short this is how neural network learns:

`starts with random numbers --> tensor operations --> update random numbers to try and make them better representation of data --> again --> again --> again`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed.**


In [90]:
import torch

# Create random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_A)
print(random_tensor_A == random_tensor_B)

tensor([[0.4841, 0.5987, 0.3125, 0.5620],
        [0.4253, 0.7354, 0.1594, 0.4910],
        [0.6031, 0.0733, 0.9055, 0.6209]])
tensor([[0.4841, 0.5987, 0.3125, 0.5620],
        [0.4253, 0.7354, 0.1594, 0.4910],
        [0.6031, 0.0733, 0.9055, 0.6209]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create random tensors
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (makes computations faster)

### 1. Getting a GPU
1. Easiest - Use Google colab for free or use the paid versions
2. Use your own GPU: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/ refer this article for recommendations
3. Use cloud computing

Refer PyTorch documentation to go with steps 2, 3 https://pytorch.org/get-started/locally/

In [92]:
!nvidia-smi

Sat Sep  7 22:20:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [93]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [94]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For PyTorch since it's capable of running compute on GPU or CPU, it's best practise to setup ddevice agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

Eg. Run on GPU if available, else default to CPU

In [95]:
# Count number of device
torch.cuda.device_count()

1

## 3. Putting tensors (and models ) on the GPU
the reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [96]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [97]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to CPU

In [98]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [99]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu  = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [100]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')