In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
               
              [[10, 11, 12],
              [13,14,15],
              [16, 17, 18]]])


In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
#Create DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)

In [15]:
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating arrays

In [16]:
sample_array = np.array([1, 2, 3])


In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))


In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2, 3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)
#ap.arange(start, stop, step)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size = (3, 5))

In [27]:
random_array

array([[3, 2, 7, 1, 9],
       [1, 9, 4, 3, 9],
       [6, 3, 4, 7, 8]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.39435973, 0.30502657, 0.47117462],
       [0.34668415, 0.78066097, 0.08719752],
       [0.77071723, 0.66813424, 0.79876668],
       [0.73986905, 0.41850644, 0.07303291],
       [0.32116941, 0.03066404, 0.45001802]])

In [33]:
#Psuedo random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size= (5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [34]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [35]:
np.unique (random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1[0]

1

In [37]:
a2[1]

array([4, 5, 6])

In [38]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a2[1]

array([4, 5, 6])

In [40]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))

In [42]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [43]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [44]:
#Get the first 4 numbers of the innermost arrays
a4[:, :, :, :1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

 ## Manipulating and comparing arrays

### Arithmetic 

In [45]:
a1

array([1, 2, 3])

In [46]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
ones = np.ones(3)

In [48]:
a1+ones

array([2., 3., 4.])

In [49]:
a1 - ones

array([0., 1., 2.])

In [50]:
a1*ones

array([1., 2., 3.])

In [51]:
a2 

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [55]:
a1/ones

array([1., 2., 3.])

In [56]:
#Floor division
a2//4

array([[0, 0, 0],
       [1, 1, 1]], dtype=int32)

In [57]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [58]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [59]:
np.add(a1, ones)

array([2., 3., 4.])

In [60]:
a1%2

array([1, 0, 1], dtype=int32)

In [61]:
a2%2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [62]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [63]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Aggregation = performing the same operation on a number of things

In [64]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [65]:
sum(listy_list)

6

In [66]:
a1

array([1, 2, 3])

In [67]:
sum(a1)

6

In [68]:
np.sum(a1)

6

In [70]:
#Use pythons's method [sum()] on py data types and NumPy's methods [np.sum()]on Numpy datatypes

In [71]:
np.mean(a2)

3.5

In [72]:
np.max(a2)

6

In [73]:
np.mean(a2)

3.5

In [76]:
# Measure of wideness from mean
np.std(a2)

1.707825127659933

In [77]:
#Higher variance, higher the range of values and vice versa
np.var(a2)

2.9166666666666665

### Reshaping and transposing

In [78]:
a2.shape

(2, 3)

In [79]:
a3.shape

(2, 3, 3)

In [80]:
#we try to multiply, but we can't

In [82]:
a2.reshape(2, 3, 1).shape

(2, 3, 1)

In [83]:
a2_reshape = a2.reshape(2, 3, 1)

In [84]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [85]:
#Transpose
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
a2.T.shape

(3, 2)

## Dot product 

In [87]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5, 3))
mat2 = np.random.randint(10, size = (5, 3))

In [88]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [89]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [91]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [92]:
#Element wise multiplication
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [93]:
#Dot product
np.dot (mat1, mat2.reshape(3, 5))

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [97]:
mat3 = np.dot(mat1, mat2.T)

In [98]:
mat3.shape

(5, 5)

## Comparision Operators

In [100]:
a1

array([1, 2, 3])

In [101]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [105]:
bool_array = a1>=a2

In [106]:
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [107]:
a1>5

array([False, False, False])

In [108]:
a1<5

array([ True,  True,  True])

In [109]:
a1 == a1

array([ True,  True,  True])

In [110]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting array

In [111]:
random_array = np.random.randint(10, size = (3, 5))

In [112]:
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [113]:
random_array.shape

(3, 5)

In [117]:
#Sorts values
np.sort(random_array)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [118]:
#Sorts indexes
np.argsort(random_array)

array([[3, 0, 1, 4, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 4, 0, 1]], dtype=int64)

In [123]:
np.argmin(random_array)

8

In [121]:
np.argmax(random_array, axis = 0)

array([2, 2, 0, 2, 2], dtype=int64)

In [122]:
np.argmax(random_array, axis = 1)

array([2, 2, 0], dtype=int64)

In [ ]:
# df = pd.DataFrame([1, 2, 4],
# index = [1, 2, 3],
# columns = ["head1", "head2", "head3"])